### ISSUE TITLE
error in S3DIS indoor segmentation

### ISSUE THREAD

**Issue by 1625368821** [hrzhou2/AdaptConv-master#8]
Hello, dear author, after I downloaded the S3DIS data set, I encountered the following error when I was executing _python train.py_. I hope the author can help me solve this problem.
你好，亲爱的作者，我下载好S3DIS数据集后，当我在执行到python train.py的时候，我遇到了以下错误，希望作者能帮助我解决这个问题。
Cloud Area_4 - Room 21/49 : storage_4
Cloud Area_4 - Room 22/49 : hallway_13
Cloud Area_4 - Room 23/49 : storage_3
Cloud Area_4 - Room 24/49 : office_9
/home/lil/AdaptConv-master-main/sem_seg/datasets/S3DIS.py:678: UserWarning: loadtxt: Empty input file: "./data/Stanford3dDataset_v1.2/Area_4/office_9/Annotations/chair_3.txt"
  object_data = np.loadtxt(object_file, dtype=np.float32)
Traceback (most recent call last):
  File "/home/lil/AdaptConv-master-main/sem_seg/train.py", line 766, in <module>
    main()
  File "/home/lil/AdaptConv-master-main/sem_seg/train.py", line 226, in main
    training_dataset = S3DISDataset(config, args.dataset, set='training', use_potentials=True)
  File "/home/lil/AdaptConv-master-main/sem_seg/datasets/S3DIS.py", line 133, in __init__
    self.prepare_S3DIS_ply()
  File "/home/lil/AdaptConv-master-main/sem_seg/datasets/S3DIS.py", line 681, in prepare_S3DIS_ply
    cloud_points = np.vstack((cloud_points, object_data[:, 0:3].astype(np.float32)))
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

Thanks

**Comment by hrzhou2** [comment]
Check this file: ./data/Stanford3dDataset_v1.2/Area_4/office_9/Annotations/chair_3.txt

It should be something but the loading function gets an empty array, which may lead to the error. You may check the dataset or download it again.

**Comment by 1625368821** [comment]
Thank you very much for your reply. This problem has been solved, but a new mistake has appeared. The new mistake is as follows.I would like to ask why such mistakes occur and the solution
非常感谢你的回复，这个问题解决了，但又出现了新的错误，新错误如下，我想问一下为什么会出现这样的错误以及解决方法
   (5): UnaryBlock(in_feat: 768, out_feat: 256, BN: True, ReLU: True)
    (6): NearestUpsampleBlock(layer: 1 -> 0)
    (7): UnaryBlock(in_feat: 384, out_feat: 128, BN: True, ReLU: True)
  )
  (head_mlp): UnaryBlock(in_feat: 128, out_feat: 128, BN: False, ReLU: True)
  (head_softmax): UnaryBlock(in_feat: 128, out_feat: 13, BN: False, ReLU: True)
  (criterion): CrossEntropyLoss()
  (l1): L1Loss()
)

*************************************

Model size 15767693

*************************************

Done in 0.1s

Start training
**************
Traceback (most recent call last):
  File "/home/lil/AdaptConv-master-main/sem_seg/train.py", line 766, in <module>
    main()
  File "/home/lil/AdaptConv-master-main/sem_seg/train.py", line 279, in main
    trainer.train(net, training_loader, test_loader, config)
  File "/home/lil/AdaptConv-master-main/sem_seg/train.py", line 438, in train
    torch.cuda.synchronize(self.device)
  File "/home/lil/miniconda2/envs/pointcloud/lib/python3.9/site-packages/torch/cuda/__init__.py", line 400, in synchronize
    _lazy_init()
  File "/home/lil/miniconda2/envs/pointcloud/lib/python3.9/site-packages/torch/cuda/__init__.py", line 164, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Thanks
